# Generated by Django 5.1.7 on 2025-04-14 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0004_product_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='explanation',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
